ALTER TABLE REZERVACIJA DROP CONSTRAINT RZRVACIJAKNJGsifra
ALTER TABLE KnjigaAutori DROP CONSTRAINT KnjgutorisfrKnjige
ALTER TABLE KnjigaAutori DROP CONSTRAINT KnjgAutorisfrutora
ALTER TABLE KnjigaIzdavac DROP CONSTRAINT Knjgzdvacsfrzdvaca
ALTER TABLE KnjigaIzdavac DROP CONSTRAINT KnjgzdavacsfrKnjge
ALTER TABLE PredmetKnjiga DROP CONSTRAINT PrdmtKnjgsfrPrdmta
ALTER TABLE PredmetKnjiga DROP CONSTRAINT PrdmtKnjgasfrKnjge
ALTER TABLE KnjigaPrimjerak DROP CONSTRAINT KnjgPrmjrsfrPrmjrk
ALTER TABLE KnjigaPrimjerak DROP CONSTRAINT KnjgPrmjraksfrKnjg
ALTER TABLE NastavnikPredmet DROP CONSTRAINT NstvnkPrdmsfrPrdmt
ALTER TABLE NastavnikPredmet DROP CONSTRAINT NstvnkPrdsfrNstvnk
ALTER TABLE KorisnikPrimjerka DROP CONSTRAINT KrsnkPrmjrsfrKrsnk
ALTER TABLE KorisnikPrimjerka DROP CONSTRAINT KrsnkPrmjsfrPrmjrk
ALTER TABLE KorisnikRezervacija DROP CONSTRAINT KrsnkRzrvsfrRzrvcj
ALTER TABLE KorisnikRezervacija DROP CONSTRAINT KrsnkRzrvcsfrKrsnk
DROP TABLE AUTOR
DROP TABLE IZDAVAC
DROP TABLE KNJIGA
DROP TABLE KorisnickiProfil
DROP TABLE PREDMET
DROP TABLE PRIMJERAK
DROP TABLE REZERVACIJA
DROP TABLE KnjigaAutori
DROP TABLE KnjigaIzdavac
DROP TABLE PredmetKnjiga
DROP TABLE KnjigaPrimjerak
DROP TABLE NastavnikPredmet
DROP TABLE KorisnikPrimjerka
DROP TABLE KorisnikRezervacija
DELETE FROM SEQUENCE WHERE SEQ_NAME = 'SEQ_GEN_TABLE'
DELETE FROM SEQUENCE WHERE SEQ_NAME = 'SEQ_GEN'
